/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AppVerificationRouteImport } from './routes/app.verification'
import { Route as AppTradingRouteImport } from './routes/app.trading'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReferralRouteImport } from './routes/app.referral'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppLeaderboardsRouteImport } from './routes/app.leaderboards'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppCopyTradingRouteImport } from './routes/app.copy-trading'
import { Route as AppCompetitionsRouteImport } from './routes/app.competitions'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMarketsRouteImport } from './routes/admin.markets'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'
import { Route as AdminCompetitionsRouteImport } from './routes/admin.competitions'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AppWalletIndexRouteImport } from './routes/app.wallet.index'
import { Route as AppWalletWithdrawRouteImport } from './routes/app.wallet.withdraw'
import { Route as AppWalletDepositRouteImport } from './routes/app.wallet.deposit'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as ApiAdminSplatRouteImport } from './routes/api/admin/$'
import { Route as ApiAdminDepositsPaymentSettingsRouteImport } from './routes/api/admin/deposits/payment-settings'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppVerificationRoute = AppVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppRoute,
} as any)
const AppTradingRoute = AppTradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReferralRoute = AppReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardsRoute = AppLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppCopyTradingRoute = AppCopyTradingRouteImport.update({
  id: '/copy-trading',
  path: '/copy-trading',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitionsRoute = AppCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketsRoute = AdminMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AppWalletIndexRoute = AppWalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWalletRoute,
} as any)
const AppWalletWithdrawRoute = AppWalletWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppWalletRoute,
} as any)
const AppWalletDepositRoute = AppWalletDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AppWalletRoute,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSplatRoute = ApiAdminSplatRouteImport.update({
  id: '/api/admin/$',
  path: '/api/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDepositsPaymentSettingsRoute =
  ApiAdminDepositsPaymentSettingsRouteImport.update({
    id: '/api/admin/deposits/payment-settings',
    path: '/api/admin/deposits/payment-settings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading': typeof TradingRoute
  '/verify': typeof VerifyRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/competitions': typeof AppCompetitionsRoute
  '/app/copy-trading': typeof AppCopyTradingRoute
  '/app/history': typeof AppHistoryRoute
  '/app/leaderboards': typeof AppLeaderboardsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trading': typeof AppTradingRoute
  '/app/verification': typeof AppVerificationRoute
  '/app/wallet': typeof AppWalletRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/app/wallet/deposit': typeof AppWalletDepositRoute
  '/app/wallet/withdraw': typeof AppWalletWithdrawRoute
  '/app/wallet/': typeof AppWalletIndexRoute
  '/api/admin/deposits/payment-settings': typeof ApiAdminDepositsPaymentSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading': typeof TradingRoute
  '/verify': typeof VerifyRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/competitions': typeof AppCompetitionsRoute
  '/app/copy-trading': typeof AppCopyTradingRoute
  '/app/history': typeof AppHistoryRoute
  '/app/leaderboards': typeof AppLeaderboardsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trading': typeof AppTradingRoute
  '/app/verification': typeof AppVerificationRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/app/wallet/deposit': typeof AppWalletDepositRoute
  '/app/wallet/withdraw': typeof AppWalletWithdrawRoute
  '/app/wallet': typeof AppWalletIndexRoute
  '/api/admin/deposits/payment-settings': typeof ApiAdminDepositsPaymentSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading': typeof TradingRoute
  '/verify': typeof VerifyRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/markets': typeof AdminMarketsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/competitions': typeof AppCompetitionsRoute
  '/app/copy-trading': typeof AppCopyTradingRoute
  '/app/history': typeof AppHistoryRoute
  '/app/leaderboards': typeof AppLeaderboardsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/profile': typeof AppProfileRoute
  '/app/referral': typeof AppReferralRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trading': typeof AppTradingRoute
  '/app/verification': typeof AppVerificationRoute
  '/app/wallet': typeof AppWalletRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/app/wallet/deposit': typeof AppWalletDepositRoute
  '/app/wallet/withdraw': typeof AppWalletWithdrawRoute
  '/app/wallet/': typeof AppWalletIndexRoute
  '/api/admin/deposits/payment-settings': typeof ApiAdminDepositsPaymentSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/blog'
    | '/contact'
    | '/education'
    | '/faq'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/markets'
    | '/platform'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/trading'
    | '/verify'
    | '/admin/cms'
    | '/admin/competitions'
    | '/admin/deposits'
    | '/admin/faqs'
    | '/admin/kyc'
    | '/admin/login'
    | '/admin/markets'
    | '/admin/media'
    | '/admin/news'
    | '/admin/referrals'
    | '/admin/roles'
    | '/admin/testimonials'
    | '/admin/users'
    | '/app/competitions'
    | '/app/copy-trading'
    | '/app/history'
    | '/app/leaderboards'
    | '/app/notifications'
    | '/app/orders'
    | '/app/portfolio'
    | '/app/profile'
    | '/app/referral'
    | '/app/settings'
    | '/app/trading'
    | '/app/verification'
    | '/app/wallet'
    | '/admin/'
    | '/app/'
    | '/api/admin/$'
    | '/api/admin/dashboard'
    | '/api/admin/users'
    | '/app/wallet/deposit'
    | '/app/wallet/withdraw'
    | '/app/wallet/'
    | '/api/admin/deposits/payment-settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/education'
    | '/faq'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/markets'
    | '/platform'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/trading'
    | '/verify'
    | '/admin/cms'
    | '/admin/competitions'
    | '/admin/deposits'
    | '/admin/faqs'
    | '/admin/kyc'
    | '/admin/login'
    | '/admin/markets'
    | '/admin/media'
    | '/admin/news'
    | '/admin/referrals'
    | '/admin/roles'
    | '/admin/testimonials'
    | '/admin/users'
    | '/app/competitions'
    | '/app/copy-trading'
    | '/app/history'
    | '/app/leaderboards'
    | '/app/notifications'
    | '/app/orders'
    | '/app/portfolio'
    | '/app/profile'
    | '/app/referral'
    | '/app/settings'
    | '/app/trading'
    | '/app/verification'
    | '/admin'
    | '/app'
    | '/api/admin/$'
    | '/api/admin/dashboard'
    | '/api/admin/users'
    | '/app/wallet/deposit'
    | '/app/wallet/withdraw'
    | '/app/wallet'
    | '/api/admin/deposits/payment-settings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/blog'
    | '/contact'
    | '/education'
    | '/faq'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/markets'
    | '/platform'
    | '/pricing'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/trading'
    | '/verify'
    | '/admin/cms'
    | '/admin/competitions'
    | '/admin/deposits'
    | '/admin/faqs'
    | '/admin/kyc'
    | '/admin/login'
    | '/admin/markets'
    | '/admin/media'
    | '/admin/news'
    | '/admin/referrals'
    | '/admin/roles'
    | '/admin/testimonials'
    | '/admin/users'
    | '/app/competitions'
    | '/app/copy-trading'
    | '/app/history'
    | '/app/leaderboards'
    | '/app/notifications'
    | '/app/orders'
    | '/app/portfolio'
    | '/app/profile'
    | '/app/referral'
    | '/app/settings'
    | '/app/trading'
    | '/app/verification'
    | '/app/wallet'
    | '/admin/'
    | '/app/'
    | '/api/admin/$'
    | '/api/admin/dashboard'
    | '/api/admin/users'
    | '/app/wallet/deposit'
    | '/app/wallet/withdraw'
    | '/app/wallet/'
    | '/api/admin/deposits/payment-settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradingRoute: typeof TradingRoute
  VerifyRoute: typeof VerifyRoute
  ApiAdminSplatRoute: typeof ApiAdminSplatRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAdminDepositsPaymentSettingsRoute: typeof ApiAdminDepositsPaymentSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verification': {
      id: '/app/verification'
      path: '/verification'
      fullPath: '/app/verification'
      preLoaderRoute: typeof AppVerificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trading': {
      id: '/app/trading'
      path: '/trading'
      fullPath: '/app/trading'
      preLoaderRoute: typeof AppTradingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/referral': {
      id: '/app/referral'
      path: '/referral'
      fullPath: '/app/referral'
      preLoaderRoute: typeof AppReferralRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboards': {
      id: '/app/leaderboards'
      path: '/leaderboards'
      fullPath: '/app/leaderboards'
      preLoaderRoute: typeof AppLeaderboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copy-trading': {
      id: '/app/copy-trading'
      path: '/copy-trading'
      fullPath: '/app/copy-trading'
      preLoaderRoute: typeof AppCopyTradingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitions': {
      id: '/app/competitions'
      path: '/competitions'
      fullPath: '/app/competitions'
      preLoaderRoute: typeof AppCompetitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/markets': {
      id: '/admin/markets'
      path: '/markets'
      fullPath: '/admin/markets'
      preLoaderRoute: typeof AdminMarketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/wallet/': {
      id: '/app/wallet/'
      path: '/'
      fullPath: '/app/wallet/'
      preLoaderRoute: typeof AppWalletIndexRouteImport
      parentRoute: typeof AppWalletRoute
    }
    '/app/wallet/withdraw': {
      id: '/app/wallet/withdraw'
      path: '/withdraw'
      fullPath: '/app/wallet/withdraw'
      preLoaderRoute: typeof AppWalletWithdrawRouteImport
      parentRoute: typeof AppWalletRoute
    }
    '/app/wallet/deposit': {
      id: '/app/wallet/deposit'
      path: '/deposit'
      fullPath: '/app/wallet/deposit'
      preLoaderRoute: typeof AppWalletDepositRouteImport
      parentRoute: typeof AppWalletRoute
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/$': {
      id: '/api/admin/$'
      path: '/api/admin/$'
      fullPath: '/api/admin/$'
      preLoaderRoute: typeof ApiAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deposits/payment-settings': {
      id: '/api/admin/deposits/payment-settings'
      path: '/api/admin/deposits/payment-settings'
      fullPath: '/api/admin/deposits/payment-settings'
      preLoaderRoute: typeof ApiAdminDepositsPaymentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarketsRoute: typeof AdminMarketsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCmsRoute: AdminCmsRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminKycRoute: AdminKycRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarketsRoute: AdminMarketsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppWalletRouteChildren {
  AppWalletDepositRoute: typeof AppWalletDepositRoute
  AppWalletWithdrawRoute: typeof AppWalletWithdrawRoute
  AppWalletIndexRoute: typeof AppWalletIndexRoute
}

const AppWalletRouteChildren: AppWalletRouteChildren = {
  AppWalletDepositRoute: AppWalletDepositRoute,
  AppWalletWithdrawRoute: AppWalletWithdrawRoute,
  AppWalletIndexRoute: AppWalletIndexRoute,
}

const AppWalletRouteWithChildren = AppWalletRoute._addFileChildren(
  AppWalletRouteChildren,
)

interface AppRouteChildren {
  AppCompetitionsRoute: typeof AppCompetitionsRoute
  AppCopyTradingRoute: typeof AppCopyTradingRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLeaderboardsRoute: typeof AppLeaderboardsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReferralRoute: typeof AppReferralRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTradingRoute: typeof AppTradingRoute
  AppVerificationRoute: typeof AppVerificationRoute
  AppWalletRoute: typeof AppWalletRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompetitionsRoute: AppCompetitionsRoute,
  AppCopyTradingRoute: AppCopyTradingRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLeaderboardsRoute: AppLeaderboardsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppProfileRoute: AppProfileRoute,
  AppReferralRoute: AppReferralRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTradingRoute: AppTradingRoute,
  AppVerificationRoute: AppVerificationRoute,
  AppWalletRoute: AppWalletRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradingRoute: TradingRoute,
  VerifyRoute: VerifyRoute,
  ApiAdminSplatRoute: ApiAdminSplatRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAdminDepositsPaymentSettingsRoute: ApiAdminDepositsPaymentSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
